"""Publish the evidence-derived presentation to the real repositories.

Everything here writes to GitHub-facing surfaces only:

  .github-art/surfaces/*.svg   the animated surface set
  README.md                    a refreshed evidence + visuals section
  description / topics / homepage   repository About metadata

Product source is never read for modification and never written. Existing
files are preserved: every commit is built on the current tip of the actual
default branch via base_tree, so this is additive, never a replacement.

Commits are created through the Git Data API so a whole repository lands in
one commit (one tree, one commit, one ref update) instead of one API call per
file.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import pathlib
import random
import re
import subprocess
import sys
import time

HERE = pathlib.Path(__file__).resolve().parent
PROFILE = HERE.parents[2]
ART = PROFILE / ".github-art" / "v8-art"
ART_DIR = ".github-art/surfaces"
OWNER = "M4G3LL4N0"

BEGIN = "<!-- TRILLIONX:presentation:begin -->"
END = "<!-- TRILLIONX:presentation:end -->"

MARKET = "https://raw.githubusercontent.com"


class GitHub:
    def __init__(self) -> None:
        self.calls = 0
        self.retries = 0

    def api(self, method: str, path: str, *, body: dict | None = None,
            raw: list | None = None, expect_json: bool = True):
        cmd = ["gh", "api", "-X", method, path]
        if body is not None:
            cmd += ["--input", "-"]
        elif raw is not None:
            cmd += raw
        delay = 1.0
        for attempt in range(7):
            if body is not None:
                proc = subprocess.run(cmd, input=json.dumps(body), capture_output=True,
                                      text=True)
            else:
                proc = subprocess.run(cmd, capture_output=True, text=True)
            if proc.returncode == 0:
                self.calls += 1
                if not expect_json:
                    return proc.stdout
                return json.loads(proc.stdout) if proc.stdout.strip() else {}
            err = proc.stderr or ""
            transient = any(s in err for s in
                            ("secondary rate limit", "abuse detection", "503",
                             "502", "504", "Bad gateway", "timeout"))
            if transient and attempt < 6:
                self.retries += 1
                time.sleep(delay + random.uniform(0, 1.2))
                delay = min(delay * 2, 45)
                continue
            raise RuntimeError(
                f"{method} {path} -> {err.strip()[:300]}"
                + (f" | body: {json.dumps(body)[:220]}" if body else "")
            )
        raise RuntimeError(f"{method} {path} exhausted retries")


def picture_block(branch: str, repo: str, slots: list[str]) -> str:
    """Markdown <picture> block, dark default, light and reduced fallbacks."""
    base = f"{MARKET}/{OWNER}/{repo}/{branch}/{ART_DIR}"
    out = [BEGIN, "", "### Animated surfaces", "",
           "Generated from this repository's own source tree: every count, route "
           "and module below was measured, not written by hand.", ""]
    titles = {
        "hero": "Identity", "terminal": "Entry points", "architecture": "Modules",
        "data_flow": "Routes", "state_machine": "Primitives",
        "component_map": "Composition", "build": "Build and tests",
        "workflow": "Workflow", "domain": "Domain", "footer": "Identity object",
    }
    for slot in slots:
        # render_art.py names the dark default <slot>.svg, not <slot>-dark.svg.
        # Pointing the README at the wrong stem silently breaks every image.
        title = titles.get(slot, slot)
        out += [
            f"#### {title}",
            "",
            "<picture>",
            f'  <source media="(prefers-reduced-motion: reduce)" srcset="{base}/{slot}-reduced.svg">',
            f'  <source media="(prefers-color-scheme: light)" srcset="{base}/{slot}-light.svg">',
            f'  <img alt="{title} diagram for {repo}" src="{base}/{slot}.svg">',
            "</picture>",
            "",
        ]
    out.append(END)
    return "\n".join(out)


def evidence_section(desc: str, slots: list[str], d: dict) -> str:
    ev = d["evidence"]
    lines = [BEGIN.replace("presentation", "evidence"), ""]
    lines += ["## What is measurable here", "",
              "Generated by `.github-art` from the source tree at publish time.", "",
              "| Signal | Value |", "| --- | --- |",
              f"| HTTP routes | {len(ev['routes'])} |",
              f"| Entry points | {len(ev['entry_points'])} |",
              f"| Module roots | {len(ev['modules'])} |",
              f"| Test files | {ev['test_count']} |",
              f"| CI workflows | {len(ev['ci_workflows'])} |",
              f"| Distinctive stack | {', '.join(ev.get('distinctive_frameworks') or []) or 'scaffold only'} |",
              f"| Status | {d['status']} |",
              f"| Evidence confidence | {d['confidence']} |",
              f"| Animated surfaces | {len(slots)} |", ""]
    lines.append(END.replace("presentation", "evidence"))
    return "\n".join(lines)


def splice_readme(existing: str, block: str, marker_begin: str, marker_end: str,
                  heading: str) -> str:
    """Insert or replace a marked block without touching surrounding content."""
    body = existing or ""
    if marker_begin in body and marker_end in body:
        head, _, rest = body.partition(marker_begin)
        _, _, tail = rest.partition(marker_end)
        return (head.rstrip("\n") + "\n\n" + block + "\n" + tail.lstrip("\n")).lstrip("\n")
    prefix = body.rstrip("\n")
    if not prefix:
        prefix = f"# {heading}\n"
    return prefix + "\n\n" + block + "\n"


def verify_block(block: str, art_dir: pathlib.Path, base_ok: bool = True) -> list[str]:
    """Every URL in the generated block must resolve to a file that exists.

    A wrong filename stem produces a README full of broken images while the
    publish still reports success, so this is checked before any write.
    """
    problems: list[str] = []
    for m in re.finditer(r'srcset="([^"]+)"|src="([^"]+)"', block):
        url = m.group(1) or m.group(2)
        if not url.startswith(MARKET):
            continue
        parts = url.split("/")
        fname = parts[-1]
        if not (art_dir / fname).exists():
            problems.append(f"missing asset {fname}")
    return problems


def local_readme() -> str:
    path = PROFILE / "README.md"
    return path.read_text() if path.exists() else ""


def get_readme(gh: GitHub, repo: str, branch: str) -> str:

    path = "README.md"
    try:
        data = gh.api("GET", f"repos/{OWNER}/{repo}/contents/{path}?ref={branch}")
        return base64.b64decode(data["content"]).decode("utf-8", "replace")
    except Exception:
        return ""


def publish_repo(gh: GitHub, name: str, entry: dict, d: dict,
                 dry_run: bool = False, replace_readme: bool = False) -> dict:
    info = gh.api("GET", f"repos/{OWNER}/{name}")
    branch = info["default_branch"]

    art_dir = ART / name
    files = sorted(art_dir.glob("*.svg"))
    if not files:
        return {"repo": name, "status": "skipped", "why": "no art rendered"}

    slots = entry["slots"]
    block = picture_block(branch, name, slots)
    ev_block = evidence_section(entry["description"], slots, d)
    if replace_readme:
        # The profile README is fully generated; splicing would leave the
        # previous hand-written file above it with 400 stale image links.
        new_readme = local_readme()
    else:
        readme = get_readme(gh, name, branch)
        new_readme = splice_readme(readme, block, BEGIN, END, name)
        new_readme = splice_readme(new_readme, ev_block,
                                   BEGIN.replace("presentation", "evidence"),
                                   END.replace("presentation", "evidence"), name)

    tree_entries = [{
        "path": f"{ART_DIR}/{f.name}",
        "mode": "100644",
        "type": "blob",
        "content": f.read_text(),
    } for f in files]
    tree_entries.append({
        "path": "README.md", "mode": "100644", "type": "blob",
        "content": new_readme,
    })

    missing = verify_block(block, art_dir)
    if missing:
        return {"repo": name, "status": "asset-error", "why": "; ".join(missing[:4])}

    if dry_run:
        return {"repo": name, "status": "dry-run", "branch": branch,
                "files": len(tree_entries), "readme_bytes": len(new_readme)}

    ref = gh.api("GET", f"repos/{OWNER}/{name}/git/ref/heads/{branch}")
    base_sha = ref["object"]["sha"]
    base_commit = gh.api("GET", f"repos/{OWNER}/{name}/git/commits/{base_sha}")
    base_tree = base_commit["tree"]["sha"]

    tree = gh.api("POST", f"repos/{OWNER}/{name}/git/trees", body={
        "base_tree": base_tree, "tree": tree_entries,
    })
    if "sha" not in tree:
        return {"repo": name, "status": "tree-error", "detail": str(tree)[:200]}
    if tree["sha"] == base_tree:
        # Identical content: do not create an empty commit.
        return {"repo": name, "status": "unchanged", "branch": branch,
                "commit": base_sha, "files": len(tree_entries)}

    commit = gh.api("POST", f"repos/{OWNER}/{name}/git/commits", body={
        "message": f"docs: source-derived surfaces and evidence for {name}\n\n"
                   f"{len(slots)} animated surfaces (dark/light/reduced) generated from "
                   f"the measured source tree: {d['evidence'].get('files', 0)} files "
                   f"analysed, {len(d['evidence'].get('routes') or [])} routes. "
                   f"Adds {ART_DIR}/ and refreshes the README evidence table. "
                   f"No product source modified.",
        "tree": tree["sha"], "parents": [base_sha],
    })
    gh.api("PATCH", f"repos/{OWNER}/{name}/git/refs/heads/{branch}",
           body={"sha": commit["sha"], "force": False})

    meta = gh.api("PATCH", f"repos/{OWNER}/{name}", body={
        "description": entry["description"][:350],
        "homepage": d.get("homepage") or entry.get("homepage") or "",
    })
    # Topics need their own endpoint: PATCH /repos accepts the field and then
    # silently discards it, so the repository would keep stale topics forever.
    topics = gh.api("PUT", f"repos/{OWNER}/{name}/topics",
                    body={"names": entry["topics"]})
    return {"repo": name, "status": "published", "branch": branch,
            "commit": commit["sha"], "files": len(tree_entries),
            "description": meta.get("description"),
            "topics": topics.get("names", topics)}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--replace-readme", action="store_true",
                    help="overwrite README.md instead of splicing into it")
    ap.add_argument("--only", default="")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--log", default=str(PROFILE / ".github-art" / "v8-publish-log.json"))
    args = ap.parse_args()

    sys.path.insert(0, str(HERE))
    import describe as D  # noqa: E402
    import evidence as E  # noqa: E402

    manifest = json.loads((ART / "manifest.json").read_text())
    index = E.load_index()
    cards = E.load_cards()
    baseline = E.load_baseline()
    signature = E.template_signature(index)

    names = [args.only] if args.only else sorted(manifest)
    if args.limit:
        names = names[: args.limit]

    gh = GitHub()
    results = []
    for i, name in enumerate(names, 1):
        entry = manifest[name]
        d = E.build(name, index[name], cards.get(name.lower()),
                    baseline.get(name, {}), signature)
        try:
            res = publish_repo(gh, name, entry, d, dry_run=args.dry_run,
                               replace_readme=args.replace_readme or name == OWNER)
        except Exception as exc:
            res = {"repo": name, "status": "error", "why": str(exc)[:220]}
        results.append(res)
        if res["status"] in ("error", "tree-error"):
            print(f"  [{i}/{len(names)}] {name:30} {res['status']}: {res.get('why','')[:90]}")
        elif not args.only or args.limit:
            print(f"  [{i}/{len(names)}] {name:30} {res['status']} "
                  f"branch={res.get('branch')} files={res.get('files')}")

    pathlib.Path(args.log).write_text(json.dumps(results, indent=1) + "\n")
    ok = sum(1 for r in results
           if r["status"] in ("published", "dry-run", "unchanged"))
    print(f"\n  repos handled : {len(results)}")
    print(f"  ok            : {ok}")
    print(f"  api calls     : {gh.calls} (retries {gh.retries})")
    for r in results:
        if r["status"] not in ("published", "dry-run", "unchanged"):
            print(f"  !! {r['repo']}: {r['status']} {r.get('why','')[:100]}")
    return 0 if ok == len(results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
