#!/usr/bin/env python3
"""Regenerate GITHUB_V6_PROJECT_ART_PLAN.md from the committed design inputs.

The plan is derived, never hand-maintained. A hand-maintained plan drifts from
the generator within one commit, and a plan that disagrees with the artifact is
worse than no plan: it looks like a specification and is not one.

Every row is built from the dossier, the identity and the rendered plate, so the
plan states what is actually shipped rather than what was intended.

  python3 scripts/profile_art/build_art_plan.py
  python3 scripts/profile_art/build_art_plan.py --audit-only   # uniqueness gate
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

PROFILE = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROFILE / "scripts" / "profile_art"))

import repo_art as RA  # noqa: E402

DOSSIERS = PROFILE / ".github-art" / "dossiers"
IDENTITY = PROFILE / ".github-art" / "identity.json"
LEDGER = PROFILE / "github-account-ledger.json"
OUT = PROFILE / "GITHUB_V6_PROJECT_ART_PLAN.md"
OWNER = "M4G3LL4N0"

VARIANTS = ("hero-motion", "hero-dark", "hero-light", "hero-reduced",
            "social-preview")


def signature(svg: str, repo: str) -> str:
    """Structure only: names, text content and numbers removed.

    Comparing whole files would call every asset unique because each carries its
    own title. What has to be unique is the drawing, so the text nodes are
    stripped and the repository name is neutralised before hashing.
    """
    t = re.sub(re.escape(repo), "REPO", svg, flags=re.I)
    t = re.sub(r">[^<]*<", ">T<", t)
    t = re.sub(r"\s+", " ", t)
    return hashlib.sha256(t.encode()).hexdigest()[:12]


def audit(idents: dict, rows: list) -> int:
    """The uniqueness gate. Non-zero exit when the portfolio has converged.

    Checks three things separately, because each can fail on its own: the drawn
    structure of each variant, the resolved composition, and the motion story.
    A shared hero is a template; a shared palette is a recolour; a shared motion
    story is a loop applied to unrelated systems.
    """
    failures = []
    for variant in VARIANTS:
        sigs: dict[str, list[str]] = defaultdict(list)
        for repo, d, ident in rows:
            svg = RA.render(d, ident, variant.replace("social-preview", "motion")
                            if variant == "social-preview" else variant)
            sigs[signature(svg, repo)].append(repo)
        groups = [v for v in sigs.values() if len(v) > 1]
        print(f"  {variant:<16} {len(sigs):>3} distinct structures "
              f"across {len(rows)} projects")
        for g in groups[:4]:
            failures.append(f"{variant}: identical drawing for {g}")

    comps: dict[tuple, list[str]] = defaultdict(list)
    for repo, _, ident in rows:
        comps[(ident["family"], ident["motif"], ident["material"],
               ident["topology"], ident["depth"], ident["accent"])].append(repo)
    for g in [v for v in comps.values() if len(v) > 1]:
        failures.append(f"shared composition: {g}")

    stories: dict[str, list[str]] = defaultdict(list)
    for repo, d, _ in rows:
        stories[(d.get("animation_metaphor") or "")].append(repo)
    print(f"  motion stories   {len(stories):>3} distinct across {len(rows)} projects")

    if failures:
        for f in failures:
            print(f"  FAIL {f}")
        return 1
    print("  no shared hero, palette or motion story")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUT))
    ap.add_argument("--audit-only", action="store_true",
                    help="run the uniqueness gate and exit non-zero on a clash")
    args = ap.parse_args()

    idents = json.loads(IDENTITY.read_text())["identities"]
    ledger = json.loads(LEDGER.read_text())
    records = {r["name"]: r for r in ledger["records"]}

    rows = []
    for p in sorted(DOSSIERS.glob("*.json")):
        d = json.loads(p.read_text())
        repo = d.get("github_repo", p.stem)
        ident = idents.get(repo)
        if not ident:
            continue
        rows.append((repo, d, ident))

    if args.audit_only:
        return audit(idents, rows)

    fams = Counter(i["family"] for _, _, i in rows)
    cats = Counter(d.get("project_category", "") for _, d, _ in rows)
    mats = Counter(i["material"] for _, _, i in rows)
    tops = Counter(i["topology"] for _, _, i in rows)

    out = [
        "# GITHUB V6 — PROJECT ART PLAN",
        "",
        "Generated by `scripts/profile_art/build_art_plan.py` from the committed",
        "dossiers and identities. Do not edit by hand: the plan is derived from the",
        "same inputs the generator reads, so it cannot drift from the artifacts it",
        "describes.",
        "",
        f"- projects with an art plan: **{len(rows)}**",
        f"- design families: **{len(fams)}** · categories: **{len(cats)}** · "
        f"materials: **{len(mats)}** · topologies: **{len(tops)}**",
        f"- families: {', '.join(f'{k} ({v})' for k, v in fams.most_common())}",
        "",
        "Each project ships five assets: `hero-motion.svg`, `hero-dark.svg`,",
        "`hero-light.svg`, `hero-reduced.svg` and `social-preview.svg`. The family",
        "chooses the subject and the motion primitive; the seed varies motif,",
        "material, topology, depth and accent inside that family and never selects",
        "it.",
        "",
        "| REPO | CATEGORY | FAMILY (basis) | METAPHOR | ANIMATION | STAGES | "
        "TERMINAL | MATERIAL / GEOMETRY / COLOUR |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for repo, d, ident in sorted(rows, key=lambda r: (r[2]["family"], r[0].lower())):
        stages = RA.stages_for(d, ident["family"])
        term = (d.get("verified_commands") or [{}])[0].get("command", "") or "—"
        anim = (d.get("animation_metaphor") or ident["family_claim"])[:52]
        metaphor = (d.get("primary_visual_metaphor") or ident["motif"])[:46]
        out.append(
            f"| [`{repo}`](https://github.com/{OWNER}/{repo}) "
            f"| {d.get('project_category','')} "
            f"| {ident['family']} ({ident['family_basis'][:30]}) "
            f"| {metaphor} | {anim} "
            f"| {' → '.join(stages[:3])} "
            f"| `{term}` "
            f"| {ident['material']} / {ident['topology']}·{ident['depth']} "
            f"/ {ident['accent']} |")

    # Repositories deliberately without a plan, stated rather than omitted.
    planned = {r for r, _, _ in rows}
    excluded = []
    for name, rec in sorted(records.items()):
        if name in planned or not rec.get("public_expected"):
            continue
        excluded.append((name, rec))

    out += ["", "## Repositories without an art plan", "",
            "Art is not generated for a project that has not been identified. Each",
            "of these is listed with the reason, so the gap is visible rather than",
            "absent.", "",
            "| REPO | REASON |", "|---|---|"]
    for name, rec in excluded:
        reason = (rec.get("classification") or "").replace("_", " ").lower()
        out.append(f"| `{name}` | {reason or 'unmapped; no local source'} |")

    Path(args.out).write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"art plan: {len(rows)} projects + {len(excluded)} excluded -> "
          f"{Path(args.out).name}")
    print(f"  families {len(fams)} · categories {len(cats)} · materials {len(mats)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
