#!/usr/bin/env python3
"""Render the bounded ``signal:start`` / ``signal:end`` block in README.md.

The block is a plain-text restatement of assets/profile/build-signal.json. It
exists for three reasons:

  1. Screen-reader and no-image readers get the same numbers the graphic shows,
     so the telemetry is never image-only.
  2. The number is greppable. A reader who distrusts the graphic can find the
     figure in the source.
  3. It is the one place the profile states its own measurement timestamp in
     text.

Only content between the markers is ever rewritten. Anything a human wrote by
hand outside them is left untouched, which is what makes it safe to run daily.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

PROFILE = Path(__file__).resolve().parents[2]
README = PROFILE / "README.md"
SIGNAL = PROFILE / "assets" / "profile" / "build-signal.json"
START = "<!-- signal:start -->"
END = "<!-- signal:end -->"


def render(signal: dict) -> str:
    metrics = signal.get("metrics", [])
    if not metrics:
        return "Build signal not yet generated."

    parts = ["<!-- Generated by scripts/profile_art/render_signal_block.py from",
             "     assets/profile/build-signal.json. Do not edit by hand. -->",
             "",
             "| Metric | Value | What it counts |",
             "| --- | --- | --- |"]
    for metric in metrics:
        # Labels are authored in caps for the graphic; the table wants words.
        label = metric["label"].replace("CI", "CI").title().replace("Ci", "CI")
        parts.append(f"| {label} | **{metric['display']}** | {metric.get('note', '')} |")
    parts.append("")
    parts.append(f"<sub>Measured {signal['generated_at']}. "
                 f"Source: {signal['source']}. "
                 "Stars and forks are deliberately absent: at this scale they are "
                 "not evidence.</sub>")
    return "\n".join(parts)


def main() -> int:
    if not SIGNAL.is_file():
        print(f"{SIGNAL.name} missing; run build_signal_data.py first", file=sys.stderr)
        return 1
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print("signal markers missing from README.md", file=sys.stderr)
        return 1

    signal = json.loads(SIGNAL.read_text(encoding="utf-8"))
    notes = {key: note for key, _label, note in metric_spec()}
    for metric in signal.get("metrics", []):
        metric["note"] = notes.get(metric["key"], "")

    body = render(signal)
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = f"{head}{START}\n{body}\n{END}{tail}"

    if updated == text:
        print("signal block unchanged")
        return 0
    README.write_text(updated, encoding="utf-8")
    print("signal block updated")
    return 0


def metric_spec():
    """Import the metric definitions rather than restating them."""
    sys.path.insert(0, str(PROFILE / "scripts" / "profile_art"))
    from build_signal_data import METRIC_SPEC
    return METRIC_SPEC


if __name__ == "__main__":
    raise SystemExit(main())
