#!/usr/bin/env python3
"""Render the V7 engineering-signal block into the profile README.

Replaces the previous signal, which reported "active systems" and weighted the
portfolio as a set of businesses. V7 reports what was measured and computed:
repositories, tests, CI, releases, documentation coverage, technical domains and
distinct state machines.

Only content between the signal markers is rewritten, so the hero, identity,
copy and hierarchy around it are never touched by this script.
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

PROFILE = Path(__file__).resolve().parents[2]
SIGNAL = PROFILE / "data" / "v7-signal.json"
README = PROFILE / "README.md"
START = "<!-- signal:start -->"
END = "<!-- signal:end -->"


def fmt(n: int) -> str:
    return f"{n:,}"


def main() -> int:
    if not SIGNAL.exists():
        raise SystemExit("run build_v7_signal.py first")
    s = json.loads(SIGNAL.read_text(encoding="utf-8"))
    eng = s["engineering"]
    sc = s["scope"]
    doms = list(s["technical_domains"].items())

    rows = [
        ("Public repositories", fmt(sc["public_repositories"]),
         "owned repositories visible on this account"),
        ("Tests verified", fmt(eng["measured_tests"]),
         "test cases run and recorded by an operator"),
        ("CI workflows", fmt(eng["ci_configured"]),
         "repositories with a test pipeline configured"),
        ("Releases", fmt(eng["releases"]), "tagged GitHub releases"),
        ("READMEs", fmt(eng["readmes_complete"]),
         "public repositories with real documentation"),
        ("SECURITY.md", fmt(eng["security_policies"]),
         "repositories with a published security policy"),
        ("Technical domains", fmt(len(doms)),
         "clusters derived from each project's architecture"),
        ("State machines", fmt(s["distinct_motion_stories"]),
         "distinct computational flows derived from source"),
    ]

    lines = [START,
             "<!-- Generated by scripts/profile_art/render_v7_signal.py from "
             "data/v7-signal.json. Do not edit by hand. -->",
             "",
             "| Signal | Value | What it counts |",
             "| --- | --- | --- |"]
    for label, value, note in rows:
        lines.append(f"| {label} | **{value}** | {note} |")
    lines.append("")
    if doms:
        lines.append("**Technical domains** — " +
                     " · ".join(f"{k} {v}" for k, v in doms) + "  ")
    langs = list(s.get("languages", {}).items())[:6]
    if langs:
        lines.append("")
        lines.append("**Languages** — " +
                     " · ".join(f"{k} {v}" for k, v in langs))
    lines.append("")
    now = subprocess.run(["date", "-u", "+%Y-%m-%dT%H:%M:%SZ"],
                         capture_output=True, text=True).stdout.strip()
    lines.append(f"<sub>Measured {now}. Source: reconciled repository inventory, "
                 "per-project dossiers and operator-recorded test counts. "
                 "Private and denylisted repositories are excluded from every "
                 "figure. Stars and forks are deliberately not shown.</sub>")
    lines.append(END)
    block = "\n".join(lines)

    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise SystemExit("signal markers missing from README.md")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    README.write_text(head + block + tail, encoding="utf-8")
    print(f"  signal block updated: {len(rows)} metrics, {len(doms)} domains")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())