#!/usr/bin/env python3
"""Render or remove the bounded ``upstream:start`` / ``upstream:end`` block.

The rule this encodes: an upstream section exists only when there is real
upstream work to point at. Merged pull requests inside repositories this
account owns are ordinary internal workflow, so they do not qualify.

With zero qualifying contributions the visible heading and body are removed
while the markers stay in place. An empty decorative section is worse than no
section: it implies a claim the data does not support.

Only content between the markers is rewritten.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

PROFILE = Path(__file__).resolve().parents[2]
README = PROFILE / "README.md"
SIGNAL = PROFILE / "assets" / "profile" / "build-signal.json"
START = "<!-- upstream:start -->"
END = "<!-- upstream:end -->"

# Section chrome that belongs to the generated block and is removed with it.
HEADING = "## Upstream Signal"
RULE_ABOVE = "\n---\n\n"


def render(signal: dict) -> str:
    upstream = signal.get("upstream", {})
    count = int(upstream.get("external_merged_prs") or 0)
    repos = upstream.get("repositories") or []

    if count == 0:
        return ("<!-- No upstream section is rendered: 0 pull requests have been "
                "merged into repositories this account does not own. Regenerate "
                "with render_upstream_block.py once that changes. -->")

    lines = ["<!-- Generated by scripts/profile_art/render_upstream_block.py from",
             "     assets/profile/build-signal.json. Do not edit by hand. -->",
             "",
             f"{count} merged pull request{'s' if count != 1 else ''} into "
             f"repositories this account does not own:"]
    for slug in repos:
        owner, _, name = slug.partition("/")
        lines.append(f"- [`{owner}/{name}`](https://github.com/{slug})")
    lines += ["",
              "<sub>Contribution only. No employment, endorsement, or affiliation "
              "is implied or claimed.</sub>"]
    return "\n".join(lines)


def main() -> int:
    if not SIGNAL.is_file():
        print("build-signal.json missing; run build_signal_data.py first", file=sys.stderr)
        return 1
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print("upstream markers missing from README.md", file=sys.stderr)
        return 1

    signal = json.loads(SIGNAL.read_text(encoding="utf-8"))
    body = render(signal)

    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)

    # The heading and its rule live outside the markers but belong to the
    # generated section, so they are added and removed together with the body.
    stripped = head.rstrip()
    if stripped.endswith("---"):
        stripped = stripped[: -len("---")].rstrip()

    show_section = not body.lstrip().startswith("<!-- No upstream section")

    updated = f"{stripped}\n\n{START}\n{body}\n{END}{tail}"
    if show_section:
        if HEADING not in updated:
            updated = updated.replace(f"{START}\n", f"{HEADING}\n\n{START}\n", 1)

    if updated == text:
        print("upstream block unchanged")
        return 0
    README.write_text(updated, encoding="utf-8")
    print("upstream section rendered" if show_section else "upstream section removed (0 external contributions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
